export const featuersData = [
  {
    name: "chatbot",
    image: "/images/navDropdown/chatbotPage.png",
    title: "Ask The Free NAI Chatbot",
    title2: "Ask The Free NAI Chatbot",
    higlight: "Fast, Personalized Answers.",
    higlight2: "Fast, Personalized Answers.",
    image2: "/images/navDropdown/mob/chat.jpg",
    text: "Nemati AI provides you advanced AI models such as OpenAI o1, GPT-4o, Mistral-small, Claude 3.5, and Gemini 2.0. Meet your smart, Nemati AI Chatbot, built to simplify your life. With quick responses and helpful insights, our Virtual Assistant is here to save you time and help you get things done efficiently. Powered by Conversational AI, it understands your needs and provides personalized assistance every step of the way. Whether you're managing your schedule, seeking information, or need support with tasks, our Chatbot Platform seamlessly integrates into your daily routine. Experience the future with Next-Gen Chatbot Technology that adapts to your preferences and enhances your productivity. Discover how our Smart Chatbot Innovations can transform the way you interact, making every interaction smooth and effortless. Give it a try and see how our Virtual Assistant Features can effortlessly assist you in achieving your goals. ",
    text2:
      "Nemati AI provides you advanced AI models such as OpenAI o1, GPT-4o, Mistral-small, Claude 3.5, and Gemini 2.0. Meet your smart, Nemati AI Chatbot, built to simplify your life. With quick responses and helpful insights, our Virtual Assistant is here to save you time and help you get things done efficiently. Powered by Conversational AI, it understands your needs and provides personalized assistance every step of the way. Whether you're managing your schedule, seeking information, or need support with tasks, our Chatbot Platform seamlessly integrates into your daily routine. Experience the future with Next-Gen Chatbot Technology that adapts to your preferences and enhances your productivity. Discover how our Smart Chatbot Innovations can transform the way you interact, making every interaction smooth and effortless. Give it a try and see how our Virtual Assistant Features can effortlessly assist you in achieving your goals. ",
  },
  {
    name: "grammar",
    title: "Make Your Writing Better in No Time with Grammar AI ",
    title2: "Perfect Your Writing with ",
    higlight2: "AI-Powered Grammar Checker",
    higlight: "the Free AI Grammar Checker",
    image: "/images/navDropdown/grammarPage.png",
    image2: "/images/navDropdown/mob/grammar.jpg",
    text: "Need a quick way to fix grammar issues? NAI Grammar Checker is here to help. Whether you're writing an email or a full report, this free grammar AI polishes every sentence for a professional finish. Give Grammar AI a try today and see how effortlessly it upgrades your writing.",
    text2:
      "Grammar AI corrects grammar and refines sentences, making your content more polished and professional. Try it for free to improve your writing quality.",
  },
  {
    name: "document",
    image: "/images/navDropdown/docPage.png",
    image2: "/images/navDropdown/mob/translatee.jpg",
    title: "Write Seamlessly with NAI Docs",
    title2: "Break Language Barriers with",
    higlight: "Smart, Simple, and Always Free",
    higlight2: "NAI Translation",
    text: "Need a fast, clean space to jot down your thoughts or draft a full report? NAI Document gives you a smart, distraction-free writing experience. Whether you’re brainstorming ideas, taking notes, or building something bigger, NAI helps you stay focused and organized. No downloads, no fuss—just a smooth, intuitive workspace built for creators like you. Try it out and turn your ideas into impact—effortlessly.",
    text2:
      "Translate AI offers seamless, precise translations, breaking language barriers and improving communication for documents and sentences.",
  },
  {
    name: "image",
    image: "/images/navDropdown/imagePage.png",
    image2: "/images/navDropdown/mob/image.jpg",
    title: "Create Cool and Awesome  Images with  ",
    title2: "AI-Driven Image Creation ",
    higlight: "NAI Image Generator",
    higlight2: "at Your Fingertips",
    text: "Nemati AI provides you advanced image AI models such as Dall-E-2 and Dall-E-3. AI Image Generator makes creating stunning visuals super easy. Turn your ideas into amazing Generative AI Images with just a few clicks. Whether you're crafting a simple graphic or a detailed masterpiece, our tool helps your imagination come to life effortlessly. Give our AI Image Generator a try and see your concepts transformed into beautiful images!",
    text2:
      "Image AI creates high-quality visuals, transforming concepts into stunning images with ease, perfect for both simple graphics and detailed masterpieces.",
  },
  {
    name: "humanize",
    image: "/images/navDropdown/codee.png",
    image2: "/images/navDropdown/mob/code.jpg",
    title: "Humanize Your Text with NAI",
    higlight: " Make It Natural, Make It Real",
    title2: "Streamline Your Coding with",
    higlight2: "Smart AI",
    text: "Humanize AI-Generated Text Instantly with NAI Looking to make your AI-generated content sound natural and human? NAI Humanize helps you convert robotic, formal, or overly technical writing into clear, conversational language that feels real. Whether you're editing blog posts, emails, marketing copy, or website content, NAI ensures your words resonate with readers. No complicated steps—just fast, reliable text humanization in seconds. Boost readability, increase engagement, and create authentic connections with your audience. Try NAI Humanize today — and make your content sound just like you!",
    text2:
      "Code AI provides real-time suggestions, error detection, and optimization, helping developers write efficient, cleaner code. Ideal for all skill levels.",
  },
  {
    name: "rewrite",
    image: "/images/navDropdown/reWritePage.png",
    image2: "/images/navDropdown/mob/rewrite.jpg",
    title: "Enhance Your Content with the Free NAI Rewriter",
    title2: "Enhance Your Content with",
    higlight: "The Ultimate Word Changer",
    higlight2: "Rewriting Tool",
    text: "Need to level up your writing in no time? NAI Rewriter, powered by Rewrite AI, does the heavy lifting for you. Whether you need a quick Word Changer or a full AI Rewrite, our Free AI Rewriter instantly transforms any text into polished prose. Give it a spin and watch your words shine—no hassle required!",
    text2:
      "Rewrite AI transforms content into clear, compelling writing, refining sentences or entire paragraphs with ease for polished, impressive results.",
  },
  // {
  // 	name: "chatpdf",
  // 	image: "/images/navDropdown/chatpdf.jpg",
  // 	image2: "/images/navDropdown/mob/chatpdf.jpg",
  // 	title: "Want quick PDF insights? Chat PDF AI by ",
  // 	title2: "AI-powered PDF analysis made easy.",
  // 	higlight: "Nerd Studio makes PDF Document Chat easy",
  // 	higlight2: "Chatpdf Tool",
  // 	text: "Looking for a quick way to get insights from your PDF files? Nerd Studio Chat PDF AI is here to help—no more scrolling through endless paragraphs! Just upload your file, and our advanced PDF Document Chat instantly creates AI PDF Summaries, uncovering hidden info so you can make data-driven decisions faster. Whether it’s reports, research papers, or contracts, we’ve got you covered. Experience the future of PDF analysis today!",
  // 	text2:
  // 		"Upload your PDF and let AI quickly extract insights and summaries, saving you time.",
  // },
  {
    name: "podcast",
    image: "/images/navDropdown/podcast.png",
    image2: "/images/navDropdown/mob/podcast.jpg",
    title: "How to Make an Epic Podcast Using AI",
    title2: "Create a Podcast in Minutes with AI: Here's How",
    higlight: "Create a Podcast in Minutes with AI: Here's How",
    higlight2: "Create a Podcast in Minutes with AI: Here's How",
    text: "Let's be honest — if you still make podcasts the old way, you're making it harder than it should be! Today, with Podcast AI Tools, you can turn a simple script into an interesting podcast episode quickly. Have a written script? Utilize text to podcast AI to convert it into audio that mimics human speech. Say goodbye to mechanical voices. The best part? AI Voice for Podcast can make your podcast sound like it was recorded in a professional studio. You don’t even need to use a microphone! And let's be honest, who has the time to sit and transcribe episodes? No one! That's where Podcast AI Transcription comes into play. It automatically transcribes your audio into text in mere minutes, saving you hours of labor. Struggling with ideas? Don't fret! Generative AI for Podcasts can assist you in brainstorming episode themes and even generating content for you. It's akin to having an inventive aide who never runs out of things to discuss.Frankly, if you're aiming to make your podcast unique, utilizing the Top Podcast AI Tools is a straightforward decision. Whether it's streamlining your workflow, enhancing audio clarity, or generating innovative ideas, [Brand Name] has got you covered. So, what's holding you back? Quit squandering time and commence crafting extraordinary podcast episodes with Podcast AI. Your listeners will be grateful for it! ",
    text2:
      "Upload your PDF and let AI quickly extract insights and summaries, saving you time.",
  },
];
