type AppName =
  | "translate"
  | "template"
  | "rewrite"
  | "chat"
  | "grammar"
  | "chat_pdf"
  | "highlight"
  | "text_to_image"
  | "image_to_image"
  | "image_to_upscale";

type AppsType =
  | "chat_bot"
  | "translate"
  | "ai_writer"
  | "template"
  | "text_to_image"
  | "image_to_image"
  | "image_upscale"
  | "code"
  | "grammar"
  | "highlight"
  | "chat_pdf"
  | "personal"
  | "regenerate_chat_bot"
  | "regenerate_chat_pdf"
  | "TEXT_TO_SPEECH"
  | "podcast"
  | "all_writer"
  | "humanize"
  | "mind-map";
