export const commentData = {
  comments: [
    {
      id: 101,
      user_username: "tech_savant",
      user_profile_picture: "https://example.com/tech_savant.jpg",
      created_at: "2023-07-19T14:30:45.123456",
      user_liked: false,
      user_disliked: false,
      like_count: 152,
      dislike_count: 15,
      reply_count: 8,
      text: "This is a groundbreaking development in AI technology!",
    },
    {
      id: 102,
      user_username: "skeptical_observer",
      user_profile_picture: "https://example.com/skeptical_observer.jpg",
      created_at: "2023-07-19T14:35:10.654321",
      user_liked: true,
      user_disliked: false,
      like_count: 98,
      dislike_count: 5,
      reply_count: 3,
      text: "While interesting, I'm concerned about the ethical implications.",
    },
    {
      id: 103,
      user_username: "ai_enthusiast",
      user_profile_picture: "https://example.com/ai_enthusiast.jpg",
      created_at: "2023-07-19T14:40:50.987654",
      user_liked: false,
      user_disliked: true,
      like_count: 45,
      dislike_count: 12,
      reply_count: 2,
      text: "I'm excited to see how this will be implemented in real-world applications.",
    },
    {
      id: 104,
      user_username: "ai_enthusiast",
      user_profile_picture: "https://example.com/ai_enthusiast.jpg",
      created_at: "2023-07-19T14:40:50.987654",
      user_liked: false,
      user_disliked: true,
      like_count: 45,
      dislike_count: 12,
      reply_count: 2,
      text: "I'm excited to see how this will be implemented in real-world applications.",
    },
    {
      id: 105,
      user_username: "ai_enthusiast",
      user_profile_picture: "https://example.com/ai_enthusiast.jpg",
      created_at: "2023-07-19T14:40:50.987654",
      user_liked: false,
      user_disliked: true,
      like_count: 45,
      dislike_count: 12,
      reply_count: 2,
      text: "I'm excited to see how this will be implemented in real-world applications.",
    },
  ],
  current_page: 1,
  max_pages: 2,
  total_items: 50,
};

const replyComment = {
  replies: [
    {
      id: 123,
      user_username: "john_doe",
      user_profile_picture: "https://example.com/john_doe.jpg",
      created_at: "2023-07-20T15:30:45.123456",
      user_liked: false,
      user_disliked: false,
      like_count: 42,
      dislike_count: 5,
      reply_count: 3,
      text: "This is a great point! I completely agree with you.",
      replyParent: 104,
    },
    {
      id: 124,
      user_username: "jane_smith",
      user_profile_picture: "https://example.com/jane_smith.jpg",
      created_at: "2023-07-20T15:31:10.654321",
      user_liked: true,
      user_disliked: false,
      like_count: 28,
      dislike_count: 2,
      reply_count: 0,
      text: "I see what you're saying, but have you considered the alternative perspective?",
      replyParent: 102,
    },
    {
      id: 125,
      user_username: "alex_johnson",
      user_profile_picture: "https://example.com/alex_johnson.jpg",
      created_at: "2023-07-20T15:31:50.987654",
      user_liked: false,
      user_disliked: true,
      like_count: 15,
      dislike_count: 8,
      reply_count: 1,
      text: "I'm not sure I agree with this approach. Let me explain why...",
      replyParent: 104,
    },
    {
      id: 125,
      user_username: "alex_johnson",
      user_profile_picture: "https://example.com/alex_johnson.jpg",
      created_at: "2023-07-20T15:31:50.987654",
      user_liked: false,
      user_disliked: true,
      like_count: 15,
      dislike_count: 8,
      reply_count: 1,
      text: "I'm not sure I agree with this approach. Let me explain why...",
      replyParent: 104,
    },
    {
      id: 125,
      user_username: "alex_johnson",
      user_profile_picture: "https://example.com/alex_johnson.jpg",
      created_at: "2023-07-20T15:31:50.987654",
      user_liked: false,
      user_disliked: true,
      like_count: 15,
      dislike_count: 8,
      reply_count: 1,
      text: "I'm not sure I agree with this approach. Let me explain why...",
      replyParent: 104,
    },
  ],
  current_page: 1,
  max_pages: 3,
  total_items: 25,
};
