interface Data {
  [key: string]: { title?: string; desc?: string; lang?: string[] }[];
}
export const data: Data = {
  chatbot: [
    {
      title: "What Can an AI Chatbot Really Do for You?",
      desc: "AI chatbots can do a ton of things for you! Whether it’s helping with work tasks, managing your day-to-day stuff, or even just having a quick chat, they’re like your personal virtual assistant. Tools like those from Nemati AI, powered by Conversational AI, make life simpler, faster, and way more fun. Want to know exactly what they can do? Let’s dive in and show you how these smart bots can level up your day!",
    },
    {
      title: "Summarize Text",
      desc: "Got a long article or report? No worries! Chatbot from Nemati AI is pros at breaking down big chunks of text. With Nemati Summarize AI Chat feature, they turn lengthy documents into quick, easy-to-read highlights in seconds. Perfect for students, professionals, or anyone juggling lots of info. Why waste time when your virtual assistant can do it for you?",
    },
    {
      title: "Friendly Chat",
      desc: "Need someone to talk to? Nemati Chatbots is here to engage in friendly and  interactive conversations. Using advanced AI models, it can mimic human-like responses, making interactions enjoyable. Whether you're feeling bored, need advice, or just want a virtual friend, a chatbot can brighten your day.",
    },
    {
      title: "Create Content",
      desc: "Chatbots equipped with Generative AI can help you write blog posts, social media captions, product descriptions, or even poetry! They provide quick drafts that you can refine, making content creation faster and easier.",
    },
    {
      title: "Enhance Customer Support",
      desc: "For businesses, chatbots offer seamless customer support by answering queries, resolving issues, and guiding users. With 24/7 availability and rapid responses, they improve customer satisfaction and reduce workload for human agents.",
    },
    {
      title: "Summon News Updates",
      desc: "Stay informed with chatbots that deliver the latest news, weather, and trends. They use real-time data integration to provide updates on topics you care about, ensuring you're always in the loop.",
    },
  ],
  translate: [
    {
      title: "What Can You Do with Nemati Translate AI?",
      desc: "Looking for an easy way to break language barriers? Nemati Translate AI is here to make translating smoother than ever. Whether you’re managing work across the globe, planning your next trip, or exploring new cultures, this AI translator has your back. Powered by cutting-edge AI for translation, it delivers fast, accurate, and natural results. Let’s dive into all the cool things you can do with this amazing tool!",
    },
    {
      title: "Real-Time Language Translation",
      desc: "Ever needed to translate something instantly? With Nemati Translate AI, you can translate text in real time—just type or speak, and your AI translator will handle the rest. Perfect for work emails, casual chats, or even travel emergencies, this feature ensures you’re never lost for words.",
    },
    {
      title: "Document Translation",
      desc: "Have a PDF, Word file, or another document that needs translation? Upload it, and let Nemati Translate AI handle the rest. It translates entire documents accurately and keeps the formatting intact, making it perfect for professionals and students.",
    },
    {
      title: "Why Choose Nemati Translate AI?",
      desc: "Unlike other tools, Nemati Translate AI combines the power of AI for translation with advanced Conversational AI technology to deliver translations that are fast, accurate, and natural. With features like voice recognition, real-time interactions, and support for multiple languages, it’s the perfect solution for anyone looking to break language barriers.",
    },
    {
      lang: [
        "AI English to Korean Translator",
        "AI English to Norwegian Translator",
        "AI English to Pashto Translator",
        "AI English to Polish Translator",
        "AI English to Punjabi Translator",
        "AI English to Romanian Translator",
        "AI English to Russian Translator",
        "AI English to Samoan Translator",
        "AI English to Sanskrit Translator",
        "AI English to Serbian Translator",
        "AI English to Sesotho Translator",
        "AI English to Setswana Translator",
        "AI English to Mongolian Translator",
        "AI English to Mizo Translator",
        "AI English to Krio Translator",
        "AI English to Kurdish Translator",
        "AI English to Kyrgyz Translator",
        "AI English to Latvian Translator",
        "AI English to Lithuanian Translator",
        "AI English to Luxembourgish Translator",
        "AI English to Macedonian Translator",
        "AI English to Malay Translator",
        "AI English to Malayalam Translator",
        "AI English to Maori Translator",
        "AI English to Marathi Translator",
        "AI English to Shona Translator",
        "AI English to Sindhi Translator",
        "AI English to Sinhala Translator",
        "AI English to Turkish Translator",
        "AI English to Turkmen Translator",
        "AI English to Uighur Translator",
        "AI English to Ukrainian Translator",
        "AI English to Urdu Translator",
        "AI English to Uzbek Translator",
        "AI English to Vietnamese Translator",
        "AI English to Welsh Translator",
        "AI English to Xhosa Translator",
        "AI English to Yoruba Translator",
        "AI English to Tongan Translator",
        "AI English to Thai Translator",
        "AI English to Slovak Translator",
        "AI English to Slovenian Translator",
        "AI English to Somali Translator",
        "AI English to Spanish Translator",
        "AI English to Swahili Translator",
        "AI English to Swazi Translator",
        "AI English to Swedish Translator",
        "AI English to Tagalog Translator",
        "AI English to Tajik Translator",
        "AI English to Tamil Translator",
        "AI English to Telugu Translator",
        "AI English to Zulu Translator",
        "AI English to Tigrinya Translator",
        "AI English to Nepali Translator",
        "AI English to Kirundi Translator",
        "AI English to Hebrew Translator",
        "AI English to Hausa Translator",
        "AI English to Haitian Creole Translato,r",
        "AI English to Gujarati Translator",
        "AI English to Georgian Translator",
        "AI English to Galician Translator",
        "AI English to French Translator",
        "AI English to Finnish Translator",
        "AI English to Fijian Translator",
        "AI English to Farsi (Persian) Translat,or",
        "AI English to Estonian Translator",
        "AI English to Hindi Translator",
        "AI English to Hmong Translator",
        "AI English to Khmer Translator",
        "AI English to Kazakh Translator",
        "AI English to Kannada Translator",
        "AI English to Javanese Translator",
        "AI English to Japanese Translator",
        "AI English to Irish Translator",
        "AI English to Bahasa Indonesia Transla,tor",
        "AI English to Inuktitut Translator",
        "AI English to Igbo Translator",
        "AI English to Icelandic Translator",
        "AI English to Hungarian Translator",
        "AI English to Esperanto Translator",
        "AI English to Czech Translator",
        "AI English to Italian Translator",
        "AI English to Amharic Translator",
        "AI English to Arabic Translator",
        "AI English to Armenian Translator",
        "AI English to Basque Translator",
        "AI English to Bengali Translator",
        "AI English to Azerbaijani Translator",
        "AI English to Assamese Translator",
        "AI English to Belarusian Translator",
        "AI English to Bosnian Translator",
        "AI English to Burmese Translator",
        "AI English to Cantonese Translator",
        "AI English to Catalan Translator",
        "AI English to Cebuano Translator",
        "AI English to Chichewa Translator",
        "AI English to Corsican Translator",
        "AI English to Mandarin Translator",
        "AI English to Greek Translator",
        "AI English to Danish Translator",
        "AI English to Dutch Translator",
        "AI English to Portuguese Translator",
        "AI English to Maltese Translator",
        "AI English to German Translator",
        "AI English to Croatian Translator",
        "AI English to Afrikaans Translator",
        "AI English to Dzongkha Translator",
      ],
    },
  ],
  image: [
    {
      title: "How Can Nemati Image AI Transform Your Creativity?",
      desc: "Imagine having a tool that can turn your creative ideas into stunning visuals instantly! Nemati Image AI is here to make working with images easy, fun, and fast. Whether you’re a designer, a business owner, or someone who just loves being creative, this AI image generator does it all—from creating visuals to editing photos. Let’s dive into all the amazing things you can do with it!",
    },
    {
      title: "Generate Stunning Images",
      desc: "Need a custom image for your project? Just describe it, and Nemati Image AI will create it in seconds using advanced models like DALL-E 3. Perfect for social media posts, marketing designs, or even personal projects, this AI image generator is a game-changer for anyone looking to create professional visuals effortlessly. With the power of DALL-E 3, your ideas turn into stunning, high-quality visuals with incredible accuracy and detail.",
    },
    {
      title: "Text To Images",
      desc: "Ever wanted to turn your words into visuals? Just type what you have in mind, and this AI image generator will bring it to life. Whether it’s for blogs, presentations, or social media, transforming text into engaging visuals has never been easier.",
    },
    {
      title: "Edit and Enhance Photos",
      desc: "Got a photo that needs a little magic? With Nemati Image AI, you can edit and enhance your images like a pro. Adjust lighting, remove backgrounds, upscale resolution, or add creative filters in just a few clicks. Whether you’re polishing a professional design or just touching up your personal photos, our AI-powered photo editor makes it simple and fast. Ready to give your photos a pro-level makeover? Try our AI photo editor now and take your visuals to the next level!",
    },
  ],
  chatpdf: [
    {
      title: "Ready to Make Your PDFs Work for You?",
      desc: "Stop struggling with long, complicated documents. With ChatPDF AI, you can easily ask questions, summarize key points, and extract data from your PDFs in seconds. Whether it’s a business report, a research paper, or a legal contract, this smart assistant transforms how you work with files. Let’s explore how it can save you time and effort!",
    },
    {
      title: "Ask Your PDF Anything",
      desc: "Got a question about your document? Just ask! With ChatPDF AI, you can search for specific info and get instant answers. Whether it’s a tricky section in a contract or an important detail in a report, it’s like having a personal assistant who knows your PDF inside out.",
    },
    {
      title: "Summarize Long PDFs",
      desc: "Long PDFs can be a total time-suck. But don’t worry—this AI can summarize PDFs in seconds, pulling out the key points so you can focus on what matters. Great for students, busy professionals, or anyone who wants quick answers without reading the whole thing.",
    },
  ],
  rewrite: [
    {
      title: "How Can Nemati Rewrite AI Help You?",
      desc: "Got a draft that feels clunky or not quite right? Nemati Rewrite AI is here to fix that! Whether you need to make your writing clearer, tweak the tone, or just polish it up, this tool makes it easy. Let’s check out all the cool ways it can transform your content and save you time.",
    },
    {
      title: "Optimize for SEO",
      desc: "Trying to rank on Google? The AI can rewrite your content to include the right keywords naturally, helping you get noticed without sounding robotic.",
    },
    {
      title: "Rewrite for Clarity",
      desc: "Ever feel like your writing doesn’t flow? Don’t stress—this AI cleans up your sentences, making them clear and to the point while keeping your message intact.",
    },
    {
      title: "Make It Original",
      desc: "Worried about sounding repetitive or too similar to something else? This tool paraphrases your text, giving it a fresh twist while keeping your ideas front and center.",
    },
  ],
  grammar: [
    {
      title: "How Can Nemati Grammar AI Improve Your Writing?",
      desc: "Got a grammar mistake that’s bugging you? No worries! Nemati Grammar AI is here to clean up your writing without breaking a sweat. Whether it’s an email, a school assignment, or a quick social media post, this tool makes everything look smooth and error-free. Let’s check out all the ways it can save your day!",
    },
    {
      title: "Fix Those Grammar Mistakes",
      desc: "Typos? Bad grammar? Forget about them! This AI spots all the little mistakes you might miss and fixes them in seconds. It’s like having your own personal proofreader.",
    },
    {
      title: "Match Your Tone",
      desc: "Want your writing to sound professional, casual, or somewhere in between? This tool adjusts the tone to fit exactly what you need—formal for work, friendly for chats, and everything in between.",
    },
  ],
  code: [
    {
      title: "How Can Nemati Code AI Make Coding Easier?",
      desc: "Got stuck with a coding issue? Don’t worry, Nemati Code AI has your back! Whether you’re debugging, writing new code, or trying to make your project run faster, this tool is like having a super-smart coding buddy. Let’s dive into all the ways it can make coding less of a headache!",
    },
    {
      title: "Generate Code in Seconds",
      desc: "Need a quick code snippet? Just tell the AI what you’re working on, and it’ll whip up clean, ready-to-use code instantly. This AI code generator saves you time and gets you back to building awesome things.",
    },
    {
      title: "Debug Without the Stress",
      desc: "Bugs driving you crazy? Let the AI handle them! It’ll find the problem, suggest a fix, and even explain what went wrong. No more endless hours of frustration—just fast, easy debugging.",
    },
    {
      title: "Make Your Code Faster and Cleaner",
      desc: "Got messy or slow code? No problem. The AI can optimize it for speed and clarity, so your project runs like a dream. Clean, efficient, and stress-free—just how coding should be.",
    },
    {
      title: "Learn as You Go",
      desc: "New to coding or trying something tricky? This coding assistant doesn’t just give you the answers—it shows you why they work. It’s like having a mentor who’s there whenever you need them.",
    },
  ],
};
